#! /bin/sh
### BEGIN INIT INFO
# Provides:          cstbox-1wire
# Required-Start:    $remote_fs $syslog cstbox-dbus cstbox-evtmgr owserver
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox Modbus devices support service
# Description:       This package adds to an existing CSTBox framework the support
#                    for 1-Wire interfaced devices. 
#                    It includes the models of currently support products.
### END INIT INFO

# Author: Eric Pascual <eric.pascual@cstb.fr>

DESC="CSTBox 1-Wire HAL"
INIT_SEQ=94
NAME=cstbox-onewire
DAEMON=/opt/cstbox/bin/onewired.py
DAEMON_ARGS=
INIT_VERBOSE=yes

DEPENDS=owserver

. /opt/cstbox/lib/init/init-functions

